auth:
  existingSecret: ''
  key: 'tskey-0123456789abcdef'

destination:
  ip: 10.0.0.1

sysctl:
  net.ipv4.ip_forward: 1
  net.ipv6.conf.all.forwarding: 1

hostname: 'kubernetes-tailscale-proxy'

dns:
  nameservers:
    - 100.100.100.100
  searches:
    - tailxxxxx.ts.net

image:
  name: ghcr.io/tailscale/tailscale
  pullPolicy: IfNotPresent
  tag: ''

tags: []

up:
  extra_args: ''

daemon:
  extra_args: ''
