name: Tailscale Proxy Helm Chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm.yml
      - charts/tailscale-proxy/**

jobs:

  Tailscale_Proxy:
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/helm.yml
    with:
      chart: tailscale-proxy
