name: Tailscale DERP Container Image

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/container.yml
      - containers/tailscale-derp/**
      - TAILSCALE_VERSION

jobs:

  Tailscale_Derp:
    uses: ./.github/workflows/container.yml
    with:
      container: tailscale-derp
    secrets: inherit
